const fetch = require('node-fetch');
const ANTHROPIC_API = 'https://api.anthropic.com/v1/messages';
const MODEL = 'claude-sonnet-4-20250514';
const API_KEY = process.env.ANTHROPIC_API_KEY;
const BREF_TEAM_MAP = {'Los Angeles Dodgers':'LAD','Washington Nationals':'WAS','St. Louis Cardinals':'STL','Detroit Tigers':'DET','Miami Marlins':'MIA','New York Yankees':'NYY','San Diego Padres':'SD','Boston Red Sox':'BOS','Toronto Blue Jays':'TOR','Chicago White Sox':'CWS','Cincinnati Reds':'CIN','Texas Rangers':'TEX','Philadelphia Phillies':'PHI','Colorado Rockies':'COL','Tampa Bay Rays':'TB','Minnesota Twins':'MIN','Chicago Cubs':'CHC','Cleveland Guardians':'CLE','Baltimore Orioles':'BAL','Pittsburgh Pirates':'PIT','Milwaukee Brewers':'MIL','Kansas City Royals':'KC','Seattle Mariners':'SEA','Los Angeles Angels':'LAA','Houston Astros':'HOU','Athletics':'ATH','Oakland Athletics':'ATH','Atlanta Braves':'ATL','Arizona Diamondbacks':'ARI','New York Mets':'NYM','San Francisco Giants':'SF'};
function htmlToText(html){return html.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'and').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g,' ').replace(/&#\d+;/g,'').replace(/['\u2018\u2019`]/g,'').replace(/[\u201C\u201D]/g,'"').replace(/\s{2,}/g,' ').trim();}
function sanitizeJSON(s){return s.replace(/['\u2018\u2019`]/g,'').replace(/[\x00-\x1F\x7F]/g,' ').replace(/,\s*([}\]])/g,'$1').replace(/}\s*{/g,'},{');}
function parseJSONRobust(text){text=text.replace(/```json\s*/gi,'').replace(/```\s*/gi,'').trim();const start=text.indexOf('[');const end=text.lastIndexOf(']');if(start===-1||end===-1)throw new Error('No JSON array found');const jsonStr=sanitizeJSON(text.substring(start,end+1));try{return JSON.parse(jsonStr);}catch(e){console.log('[scraper] Full parse failed, using extractor');}const games=[];const pat=/\{(?:[^{}]|\{[^{}]*\})*\}/g;let m;while((m=pat.exec(jsonStr))!==null){try{const obj=JSON.parse(sanitizeJSON(m[0]));if(obj.away_team&&obj.home_team)games.push(obj);}catch(e){}}if(games.length>0){console.log('[scraper] Extracted '+games.length+' games via fallback');return games;}throw new Error('Could not parse any games from response');}
async function callClaude(prompt,maxTokens){if(!API_KEY)throw new Error('ANTHROPIC_API_KEY not set');const resp=await fetch(ANTHROPIC_API,{method:'POST',headers:{'Content-Type':'application/json','x-api-key':API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:MODEL,max_tokens:maxTokens,messages:[{role:'user',content:prompt}]})});if(!resp.ok)throw new Error('Anthropic API error '+resp.status+': '+await resp.text());const data=await resp.json();return data.content.filter(b=>b.type==='text').map(b=>b.text).join('');}
async function fetchLineups(dateStr){console.log('[scraper] Fetching RotoWire for '+dateStr);const url='https://www.rotowire.com/baseball/daily-lineups.php?date='+dateStr;const resp=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36','Accept':'text/html'}});if(!resp.ok)throw new Error('RotoWire fetch failed: '+resp.status);const html=await resp.text();const fullText=htmlToText(html);console.log('[scraper] Text length: '+fullText.length);const markers=['Confirmed Lineup','Expected Lineup','PM ET','AM ET'];let sectionStart=fullText.length;for(const mk of markers){const idx=fullText.indexOf(mk);if(idx>0&&idx<sectionStart)sectionStart=idx;}const start=Math.max(0,sectionStart-200);const chunk=fullText.substring(start,start+35000).replace(/'/g,'').replace(/\u2019/g,'').replace(/`/g,'');const prompt='Extract ALL MLB games from this RotoWire lineup page text for '+dateStr+'. Include Confirmed AND Expected lineups. Never skip a game.\n\nCRITICAL pitcher rules:\n- awaySP = pitcher for AWAY team, pitches AGAINST home batters\n- homeSP = pitcher for HOME team, pitches AGAINST away batters\n\nDo NOT use apostrophes anywhere in the JSON output.\n\nReturn ONLY a raw JSON array:\n[{"game_id":"stl-det","away_team":"STL","home_team":"DET","time":"1:10 PM ET","lineup_status":"confirmed","away_sp":{"name":"Dustin May","hand":"R"},"home_sp":{"name":"Jack Flaherty","hand":"R"},"market_away_ml":144,"market_home_ml":-171,"market_total":7.5,"park_factor":0.96,"away_lineup":[{"slot":1,"name":"JJ Wetherholt","hand":"L"},{"slot":2,"name":"Ivan Herrera","hand":"R"}],"home_lineup":[{"slot":1,"name":"Colt Keith","hand":"L"},{"slot":2,"name":"Kevin McGonigle","hand":"L"}]}]\n\nTeams: LAD WAS STL DET MIA NYY SD BOS TOR CWS CIN TEX PHI COL TB MIN CHC CLE BAL PIT MIL KC SEA LAA HOU ATH ATL ARI NYM SF (Athletics=ATH)\nPark factors: LAD:1.00 WAS:1.02 STL:0.99 DET:0.96 MIA:1.01 NYY:1.04 SD:0.94 BOS:1.03 TOR:1.01 CWS:1.01 CIN:1.06 TEX:1.02 PHI:1.03 COL:1.16 TB:0.97 MIN:0.97 CHC:1.04 CLE:0.95 BAL:1.02 PIT:0.97 MIL:0.97 KC:0.97 SEA:0.95 LAA:0.97 HOU:1.00 ATH:0.96 ATL:1.03 ARI:1.06 NYM:1.01 SF:0.93\nHands: R=right L=left S=switch\nRaw JSON array only.\n\nPAGE TEXT:\n'+chunk;const text=await callClaude(prompt,4000);return parseJSONRobust(text);}
async function fetchScores(dateStr){console.log('[scraper] Fetching Baseball Reference for '+dateStr);const url='https://www.baseball-reference.com/boxes/?date='+dateStr;const resp=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36','Accept':'text/html'}});if(!resp.ok)throw new Error('Baseball Reference fetch failed: '+resp.status);const html=await resp.text();const text=htmlToText(html);const scores=[];const teamNames=Object.keys(BREF_TEAM_MAP);const pat=new RegExp('('+teamNames.map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')\\s+(\\d+)\\s+Final\\s+('+teamNames.map(t=>t.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')).join('|')+')\\s+(\\d+)','g');let m;while((m=pat.exec(text))!==null){const at=BREF_TEAM_MAP[m[1]];const ht=BREF_TEAM_MAP[m[3]];if(at&&ht)scores.push({away_team:at,home_team:ht,away_score:parseInt(m[2]),home_score:parseInt(m[4]),final:true});}console.log('[scraper] Parsed '+scores.length+' scores from Baseball Reference');return scores;}
function makeGameId(awayTeam,homeTeam){return (awayTeam+'-'+homeTeam).toLowerCase();}
module.exports={fetchLineups,fetchScores,makeGameId};
