const fetch = require('node-fetch');
const ANTHROPIC_API = 'https://api.anthropic.com/v1/messages';
const MODEL = 'claude-sonnet-4-20250514';
const API_KEY = process.env.ANTHROPIC_API_KEY;
const BREF_TEAM_MAP = {'Los Angeles Dodgers':'LAD','Washington Nationals':'WAS','St. Louis Cardinals':'STL','Detroit Tigers':'DET','Miami Marlins':'MIA','New York Yankees':'NYY','San Diego Padres':'SD','Boston Red Sox':'BOS','Toronto Blue Jays':'TOR','Chicago White Sox':'CWS','Cincinnati Reds':'CIN','Texas Rangers':'TEX','Philadelphia Phillies':'PHI','Colorado Rockies':'COL','Tampa Bay Rays':'TB','Minnesota Twins':'MIN','Chicago Cubs':'CHC','Cleveland Guardians':'CLE','Baltimore Orioles':'BAL','Pittsburgh Pirates':'PIT','Milwaukee Brewers':'MIL','Kansas City Royals':'KC','Seattle Mariners':'SEA','Los Angeles Angels':'LAA','Houston Astros':'HOU','Athletics':'ATH','Oakland Athletics':'ATH','Atlanta Braves':'ATL','Arizona Diamondbacks':'ARI','New York Mets':'NYM','San Francisco Giants':'SF'};
function htmlToText(html){return html.replace(/<script[\s\S]*?<\/script>/gi,'').replace(/<style[\s\S]*?<\/style>/gi,'').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'and').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&nbsp;/g,' ').replace(/&#\d+;/g,'').replace(/['\u2018\u2019`]/g,'').replace(/[\u201C\u201D]/g,'"').replace(/\s{2,}/g,' ').trim();}
function sanitizeJSON(s){return s.replace(/['\u2018\u2019`]/g,'').replace(/[\x00-\x1F\x7F]/g,' ').replace(/,\s*([}\]])/g,'$1').replace(/}\s*{/g,'},{');}
function parseJSONRobust(text){text=text.replace(/```json\s*/gi,'').replace(/```\s*/gi,'').trim();const start=text.indexOf('[');const end=text.lastIndexOf(']');if(start===-1||end===-1)throw new Error('No JSON array found');const jsonStr=sanitizeJSON(text.substring(start,end+1));try{return JSON.parse(jsonStr);}catch(e){console.log('[scraper] Full parse failed, using extractor');}const games=[];const pat=/\{(?:[^{}]|\{[^{}]*\})*\}/g;let m;while((m=pat.exec(jsonStr))!==null){try{const obj=JSON.parse(sanitizeJSON(m[0]));if(obj.away_team&&obj.home_team)games.push(obj);}catch(e){}}if(games.length>0){console.log('[scraper] Extracted '+games.length+' games via fallback');return games;}throw new Error('Could not parse any games from response');}
async function callClaude(prompt,maxTokens){if(!API_KEY)throw new Error('ANTHROPIC_API_KEY not set');const resp=await fetch(ANTHROPIC_API,{method:'POST',headers:{'Content-Type':'application/json','x-api-key':API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:MODEL,max_tokens:maxTokens,messages:[{role:'user',content:prompt}]})});if(!resp.ok)throw new Error('Anthropic API error '+resp.status+': '+await resp.text());const data=await resp.json();return data.content.filter(b=>b.type==='text').map(b=>b.text).join('');}
